export const listOfUsStates = [
    { content: "Alabama", value: "AL" },
    { content: "Alaska", value: "AK" },
    { content: "Arizona", value: "AZ" },
    { content: "Arkansas", value: "AR" },
    { content: "California", value: "CA" },
    { content: "Colorado", value: "CO" },
    { content: "Connecticut", value: "CT" },
    { content: "Delaware", value: "DE" },
    { content: "Florida", value: "FL" },
    { content: "Georgia", value: "GA" },
    { content: "Hawaii", value: "HI" },
    { content: "Idaho", value: "ID" },
    { content: "Illinois", value: "IL" },
    { content: "Indiana", value: "IN" },
    { content: "Iowa", value: "IA" },
    { content: "Kansas", value: "KS" },
    { content: "Kentucky", value: "KY" },
    { content: "Louisiana", value: "LA" },
    { content: "Maine", value: "ME" },
    { content: "Maryland", value: "MD" },
    { content: "Massachusetts", value: "MA" },
    { content: "Michigan", value: "MI" },
    { content: "Minnesota", value: "MN" },
    { content: "Mississippi", value: "MS" },
    { content: "Missouri", value: "MO" },
    { content: "Montana", value: "MT" },
    { content: "Nebraska", value: "NE" },
    { content: "Nevada", value: "NV" },
    { content: "New Hampshire", value: "NH" },
    { content: "New Jersey", value: "NJ" },
    { content: "New Mexico", value: "NM" },
    { content: "New York", value: "NY" },
    { content: "North Carolina", value: "NC" },
    { content: "North Dakota", value: "ND" },
    { content: "Ohio", value: "OH" },
    { content: "Oklahoma", value: "OK" },
    { content: "Oregon", value: "OR" },
    { content: "Pennsylvania", value: "PA" },
    { content: "Rhode Island", value: "RI" },
    { content: "South Carolina", value: "SC" },
    { content: "South Dakota", value: "SD" },
    { content: "Tennessee", value: "TN" },
    { content: "Texas", value: "TX" },
    { content: "Utah", value: "UT" },
    { content: "Vermont", value: "VT" },
    { content: "Virginia", value: "VA" },
    { content: "Washington", value: "WA" },
    { content: "West Virginia", value: "WV" },
    { content: "Wisconsin", value: "WI" },
    { content: "Wyoming", value: "WY" }
  ];